[binance]
b_api_key = "PLN2rokctyc4NnRNQLMp04jlRqpkW4WMLlrgeFGIpvGgggKczFrVZn0yGDk9Pcxj"
b__key = "wGN2aYzBMPZnQK0cRm397QlWXoMB51g34c1A7Qg9UkA5daCE3MUnJ3PraiKE86Sw"
b_passphrase = "YOUR_PASSPHRASE_HERE"

[hyperliquid]
hl_api_key = "YOUR_API_KEY_HERE"
hl_secret_key = "0xb94a852aff85ce17c84d19f7c09bf9e730d412e811cee5fce9fbb67e1e8aa5e1"
hl_passphrase = "YOUR_PASSPHRASE_HERE"


[behaviour]
# Performance monitor interval in seconds
monitor_interval_sec = 120
# max amount of USD to use in a single cyclic arbitrage
usd_cyclic_arbitrage = 20


[log]
file_directory = "./log"
file_prefix = "log"
file_log_level = "warn"
term_log_level = "info"
